import React, { ReactNode } from "react";
import { Footer } from "./Footer";
import { Header } from "./Header";
import Head from "next/head";
import { useIsPageRendered } from "../hooks/useIsPageRendered";
import { Blurry } from "./Blurry";

type LayoutProps = {
  children: ReactNode;
  title?: string;
  background?: string;
  message?: string;
};

export const Layout: React.FC<LayoutProps> = ({
  children,
  title,
  background,
  message,
}) => {
  const isPageRendered = useIsPageRendered();
  return (
    <>
      <Head>
        <title>{`Iyer Research Lab${title ? ` - ${title}` : ""}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blurry>
        <Header background={background} message={message} />
        <div className={`bg-gray-800`}>{children}</div>
        <Footer />
      </Blurry>
    </>
  );
};
