import Head from "next/head";
import React, { ReactNode } from "react";
import { Blurry } from "./Blurry";
import { Footer } from "./Footer";
import { Header } from "./Header";

type LayoutProps = {
  children: ReactNode;
  title?: string;
  background?: string;
  message?: string;
};

export const Layout: React.FC<LayoutProps> = ({
  children,
  title,
  background,
  message,
}) => {
  return (
    <>
      <Head>
        <title>{`Iyer Research Lab${title ? ` - ${title}` : ""}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header background={background} message={message} />
      <Blurry>
        <div className={`bg-gray-800`}>{children}</div>
      </Blurry>
      <Footer />
    </>
  );
};
